[8.0][FIX]sale_commission: Only create commissions in customer invoices.
OCA/commission pull request #100
Opened 2016-08-26 08:49 UTC by jesusVMayor

Fixes the creation of account.invoice.line.agent in supplier invoices. It occurs when a customer with agent is also an agent.

2016-08-26 09:02 UTC, pedrobaeza commented on sale_commission/models/account_invoice.py
> +    def create(self, vals):
You must not replace the default. It's there for something: modify in screen the default commission values if needed.

2016-08-27 20:57 UTC, ivantodorovich commented on sale_commission_product/models/account_invoice.py
> +        if type == 'out_invoice':
what about out_refund?

2016-08-30 09:52 UTC, jesusVMayor commented
Added out_refund.
I added a check in the settlement wizard because the only thing that prevents commissions creation for the supplier invoices its the partner_id in contexts it is not passed, and this could be changed by any module. I not see another way to improve the control of commissions creation without removing the default.

2016-11-12 02:57 UTC, pedrobaeza requested changes

2016-11-12 02:57 UTC, pedrobaeza commented on sale_commission_product/models/account_invoice.py
> +        if type in ('out_invoice', 'out_refund'):
Don't make 2 nested if, but put all conditions in one.

2016-12-27 07:20 UTC, atchuthan approved these changes
minor change as per @pedrobaeza suggestion

Could change label to Needs fixing!!

2017-05-16 08:37 UTC, jesusVMayor commented
Fixed

2017-05-16 08:58 UTC, pedrobaeza approved these changes

2017-05-16 08:58 UTC, merged