[11.0] [MIG]mig sale commission
OCA/commission pull request #135
Opened 2017-10-18 09:12 UTC by etobella

2017-10-18 13:13 UTC, rgarnau requested changes

2017-10-18 13:13 UTC, rgarnau commented on sale_commission/models/settlement.py
> +            'company_id': self.company_id.id,
When using the wizard to create the invoices for the commissions already settled, in cases where more than one agent was associated to an invoice line an error occurs. I fixed it by changing this line to:  'company_id': settlement.company_id.id,

2017-10-19 08:02 UTC, rgarnau approved these changes
Code and functional review :+1:

2017-11-08 16:25 UTC, HviorForgeFlow requested changes

2017-11-08 16:25 UTC, HviorForgeFlow commented on sale_commission/views/settlement_view.xml
> +        <field name="name">Settlments</field>
typo: Settlements

2017-11-08 16:25 UTC, HviorForgeFlow commented on sale_commission/views/settlement_view.xml
> +    <menuitem name="Settlments"
typo: Settlements

2017-11-10 15:04 UTC, JordiBForgeFlow approved these changes
:+1:

2017-11-10 15:21 UTC, HviorForgeFlow approved these changes
LGTM :+1:

2017-11-10 15:21 UTC, merged