[11.0][IMP] Adding graph view and settlement report
OCA/commission pull request #175
Opened 2018-08-07 09:00 UTC by aitorbouzas

Created graph and pivot view for settlements extracted from invoices. Added also a qweb-pdf report for the settlements.

2018-08-07 09:48 UTC, aitorbouzas commented
@pedrobaeza how can I pass through SQL injection problem? Please check my code, the problem is that psycopg2 `execute(sql, params)` encloses the param values into single quotes...

2018-08-08 08:50 UTC, pedrobaeza commented
Hi @aitorbouzas that's not the thing that makes Travis to fail, but any way, you can solve it this way:
```python
from psycopg2.extensions import AsIs
...
query = "CREATE or REPLACE VIEW %%s as ( %s FROM ( %s ) %s );" % (
    self._select(), self._from(), self._group_by(),
)
self._cr.execute(query, (AsIs(self._table), ))
```
The real problem in LINT stage is:
```
sale_commission/report/sale_commission_analysis_report.py:99:80: E501 line too long (94 > 79 characters)
```
And concerning test stages, with this patch, you'll get a proper SQL stage, so it should be OK.

2018-08-10 06:48 UTC, aitorbouzas commented
Thank you @pedrobaeza.
Just solved it.

P.S: I already signed the CLA..

2018-10-02 14:56 UTC, pedrobaeza requested changes
Is this analyzing settlements or invoices generated from the settlements? I think it should be the first one, with additional filter for seeing what is already invoiced.

2018-10-02 14:56 UTC, pedrobaeza commented on sale_commission/report/sale_commission_analysis_report.py
> +    invoice_state = fields.Selection([
For not hardcoding this and not being tolerant to extensions, what you can do it put a `selection` method and use the same technique as here:

https://github.com/OCA/sale-workflow/blob/96956205fcd1474443f93da21aaff300f7bb0282/sale_order_type/models/sale_order_type.py#L16-L18

2018-10-02 14:56 UTC, pedrobaeza commented on sale_commission/report/sale_commission_analysis_report.py
> +            LEFT JOIN account_invoice ai ON ai.id = ail.invoice_id
This one can be `INNER JOIN`

2018-10-02 14:56 UTC, pedrobaeza commented on sale_commission/report/sale_commission_analysis_report.py
> +            LEFT JOIN product_template pt ON pp.product_tmpl_id = pt.id
As well as this one

2018-10-02 14:56 UTC, pedrobaeza commented on sale_commission/report/sale_commission_analysis_report.py
> +            aila.amount,
Why do you put this amount in `group by`? All measures shouldn't be in group by.

2018-10-04 14:06 UTC, aitorbouzas commented
@pedrobaeza actually report let's you analyze line invoices that has agent commissions in them, and you can check whether it was settled or not. The initial need was to be able to estimate the amount of commissions you must pay in the future and how much did you pay.
Want me to make it so you can analyze settlements?

2018-10-04 14:09 UTC, aitorbouzas commented
Another thing: is it necessary to allow users the creation of settlements manually? I could edit the list view so we don't allow it.

2018-10-12 16:07 UTC, pedrobaeza commented
> this pivot let's you analyze line invoices that has agent commissions in them

OK, I didn't get the meaning of this. Yeah, I think it's a good idea having the filter to see if they are settled or not.

> Another thing: is it necessary to allow users the creation of settlements manually? I could edit the list view so we don't allow it.

Yes, we should prevent it as they are populated through the wizard.

2018-10-12 18:40 UTC, aitorbouzas commented
@pedrobaeza Made all the requested changes, let's see Travis and Runbot. Also edited tree view to restrict manual creation of settlements.

2018-10-13 15:03 UTC, aitorbouzas commented
Green! How's it now?

2018-11-26 21:31 UTC, pedrobaeza commented
Integrated in #190

2018-11-26 21:31 UTC, closed without merging