[IMP] Add two hooks on make settlements
OCA/commission pull request #176
Opened 2018-09-03 11:14 UTC by etobella

It only adds two hooks on the creation of settlements.

2018-09-03 11:32 UTC, pedrobaeza requested changes

2018-09-03 11:32 UTC, pedrobaeza commented on sale_commission/wizard/wizard_settle.py
> +    def _get_settlement_values(self, agent, company, sett_from, sett_to):
Call it for following the same practice as Odoo core, `_prepare_settlement_vals`

2018-09-03 11:32 UTC, pedrobaeza commented on sale_commission/wizard/wizard_settle.py
> +    def _get_settlement_domain(self, agent, company, sett_from, sett_to):
Instead of the domain, return the record you want, as you might change order or other requirement for getting a different settlement.

2018-09-03 13:40 UTC, etobella commented
@pedrobaeza Changes have been applied.

2018-09-03 14:39 UTC, JordiBForgeFlow approved these changes

2018-09-04 07:18 UTC, pedrobaeza approved these changes

2018-09-04 07:18 UTC, merged