sale_commission: propagate agents from company to contacts
OCA/commission pull request #197
Opened 2019-01-19 22:28 UTC by ernestotejeda

Cc @Tecnativa

2019-01-20 11:43 UTC, pedrobaeza reviewed
We can assign also `agents` on create when `'parent_id' in vals and agents` not in vals`

2019-01-30 08:44 UTC, cubells requested changes
You should increase the module version too.

2019-01-30 08:44 UTC, cubells commented on sale_commission/models/res_partner.py
> +        and there's no Salesperson or Sales Channel defined yet"""
This docstring I think is incorrect.

2019-02-01 14:47 UTC, ernestotejeda commented
No problem when you create a contact from * Sales -> Orders -> Customers * and you select the parent company to which it belongs, but, when the contacts are created as part of the insertion of data for the creation of the parent company; From the contact's create method, the agents of the parent company (self.browse (vals ['parent_id']). agents) returns an empty record set, so I can not pass the company's agents to those contacts.
I do not know why self.browse(vals['parent_id']).agents returns an empty record set, apparently this happens because it's a many2many field.
I can't pass this field as default by context apparently because it's a many2many field

2019-02-04 19:52 UTC, pedrobaeza commented
@ernestotejeda check last commit. With this, it's working without problems.

2019-02-04 19:53 UTC, pedrobaeza approved these changes

2019-02-05 14:58 UTC, ernestotejeda commented
I added a known issue and squash

2019-04-03 23:46 UTC, merged