[16.0][MIG] commission_formula
OCA/commission pull request #448
Opened 2023-08-30 09:52 UTC by arleite

2023-10-02 13:49 UTC, flalexg commented
Hi @arleite , I think you left the module `sale_comission_pricelist` in the MR. Could you remove it? I saw the changes of this module here: https://github.com/OCA/commission/pull/425

2023-10-11 13:31 UTC, aliciagaarzo commented
Hi @arleite ,
Reviewing the code I see it correct, except that I would launch the command to solve the pre-commit, kind regards.

2023-10-11 14:03 UTC, aliciagaarzo reviewed
Hi @arleite ,
Reviewing the code I see it correct, except that I would launch the command to solve the pre-commit, kind regards.

2023-10-11 15:18 UTC, aliciagaarzo commented
Also, if possible, I would cover the tests to solve the codecov.

2023-10-11 15:19 UTC, aliciagaarzo approved these changes
Also, if possible, I would cover the tests to solve the codecov

2023-10-17 11:32 UTC, flalexg requested changes

2023-10-17 11:32 UTC, flalexg commented on commission_formula/views/commission_view.xml
> +                            name="formula"
Could we add the widget ace here? It would better I think.

2023-10-18 07:02 UTC, flalexg approved these changes
Functional and code review. LGTM!

2023-10-18 07:03 UTC, pedrobaeza commented
/ocabot migration commission_formula
/ocabot merge nobump

2023-10-18 07:33 UTC, pedrobaeza commented
/ocabot merge nobump

2023-10-18 07:39 UTC, merged