[14.0][ADD] sale_commission_partial_payment: Commission based on payment amount
OCA/commission pull request #486
Opened 2023-12-07 15:20 UTC by odooNextev

2023-12-07 17:03 UTC, stefano-ooops approved these changes
ok funzionale

2023-12-07 18:08 UTC, francesco-ooops commented on sale_commission_partial_settlement/readme/CONTRIBUTORS.rst
> +* Nextev <web@nextev.it>
* Nextev <web@nextev.it>  
  * Matteo Tognini
* PyTech SRL <info@pytech.it>
  * Alessandro Uffreduzzi <alessandro.uffreduzzi@pytech.it>
* Ooops404 <info@ooops404.com>
  * Francesco Foresti francesco.foresti@ooops404.com

2023-12-12 10:24 UTC, aleuffre requested changes
Code review, some code cleanup but generally looks good IMO

2023-12-12 10:24 UTC, HekkiMelody commented on sale_commission_partial_settlement/models/account_move.py
> +    )
**quibble(non-blocking)**: I'm not 100% sure, but I'm 95% sure you don't need to re-declare the method's dependencies if they're already declared in the original method

2023-12-12 10:24 UTC, HekkiMelody commented on sale_commission_partial_settlement/models/account_move.py
> +            )
**issue**: We can call `super()` here instead of hard-overwriting the method.

**question**: what about the lines whose payment_amount_type is "paid"?

2023-12-12 10:24 UTC, HekkiMelody commented on sale_commission_partial_settlement/models/account_move.py
> +    settled = fields.Boolean(store=True)
**todo**: there's no need to specify `store=True` here.

2023-12-12 10:24 UTC, aleuffre commented on sale_commission_partial_settlement/wizard/wizard_settle.py
> +                    pos += 1
**thought**: this is not very pythonic.

I think there are more elegant ways of doing it, but at the very least

```py
sett_to = date.min
for line in agent_lines_company:
```

2023-12-12 10:24 UTC, aleuffre commented on sale_commission_partial_settlement/wizard/wizard_settle.py
> +            }
**quibble(non-blocking)**: can perhaps be slightly cleaner, but this is just my preference:

```suggestion
            return {
                "name": _("Created Settlements"),
                "type": "ir.actions.act_window",
                "view_type": "form",
                "view_mode": "tree,form",
                "res_model": "sale.commission.settlement",
                "domain": [("id", "in", settlement_ids)],
            }
```

2023-12-12 13:49 UTC, odooNextev commented on sale_commission_partial_settlement/models/account_move.py
> +            )
@aleuffre Thanks for the review. For 'paid' 'payment_amount_type' I'm setting 'settled' to True inside _partial_commissions method. What are your thoughts on this?

2023-12-12 14:15 UTC, aleuffre commented on sale_commission_partial_settlement/models/account_move.py
> +            )
Ah, I see, that's fair I suppose.

2023-12-12 14:16 UTC, aleuffre approved these changes
Code review, LGTM.

If there was one minor request I'd ask, it would be to move each model into its own file named like the model itself. It'd make it so much easier to browse.

Non-blocking though, I'm already approving as is.

Thank you!

2023-12-12 14:18 UTC, francesco-ooops commented
@pedrobaeza picking up from #480 , how do you judge this version? Thanks!

2023-12-12 16:20 UTC, pedrobaeza reviewed
OK, seems a better design for being more compatible.

2023-12-12 16:20 UTC, pedrobaeza commented on sale_commission_partial_settlement/readme/CONTRIBUTORS.rst
> +    * Matteo Tognini
Incorrect RST formatting.

2023-12-12 16:20 UTC, pedrobaeza commented on sale_commission_partial_settlement/static/description/icon.svg
Don't copy the same SVG if you are not going to modify it.

2023-12-12 16:38 UTC, francesco-ooops commented
@pedrobaeza one sec, we'll add USAGE :)

2023-12-13 10:58 UTC, francesco-ooops commented
@pedrobaeza ok, ready for merge!

2023-12-13 11:00 UTC, pedrobaeza commented on sale_commission_partial_settlement/readme/USAGE.rst
> +Select Payment Amount Type: Paid Amount
```suggestion
#. Go to Sales > Commissions Management > Commission Types > create or open a record
#. Select Invoice Status: Payment Based
#. Select Payment Amount Type: Paid Amount
```

2023-12-13 11:00 UTC, pedrobaeza commented on sale_commission_partial_settlement/security/ir.model.access.csv
> +access_account_invoice_line_agent_partial,access_account_invoice_line_agent_partial,model_account_invoice_line_agent_partial,base.group_user,1,1,1,1
Too open permission. I think it should be sales user at least, don't you think?

2023-12-13 11:23 UTC, pedrobaeza commented
/ocabot merge nobump

2023-12-13 11:29 UTC, merged