[17.0][MIG] account_commission: Migration to 17.0
OCA/commission pull request #499
Opened 2024-01-19 14:56 UTC by ambientWave

I upgraded the 'account_commission' module to be installed on Odoo 17.0. More focus was given to upgrading xml files.

The demo files weren't upgraded and hence, an error during installation is warning user that demo data wasn't populated. However, the module can be used without demo data.

Python code needs to be tested thoroughly.

All contributions and comments are welcomed.

2024-01-21 07:37 UTC, ambientWave commented
The following error is seen in Odoo and OCB tests:
```
odoo-addon-account_commission @ file:///__w/commission/commission/account_commission
+ pip install -r test-requirements.txt -c test-constraints.txt
WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Looking in indexes: https://wheelhouse.odoo-community.org/oca-simple-and-pypi
ERROR: Could not find a version that satisfies the requirement odoo-addon-commission<17.1dev,>=17.0dev (from versions: 15.0.2.0.0, 15.0.2.0.0.2, 15.0.2.0.0.3, 15.0.2.0.0.4, 15.0.2.0.0.6, 15.0.2.0.0.9, 15.0.2.1.0, 15.0.2.1.0.2, 15.0.2.2.0, 15.0.2.2.0.1, 15.0.2.2.0.2, 15.0.2.2.0.3, 15.0.2.2.0.5, 15.0.3.0.0, 15.0.3.1.0, 16.0.1.0.0.3, 16.0.1.0.0.4, 16.0.1.0.0.6, 16.0.1.0.0.8, 16.0.1.1.0, 16.0.1.1.1, 16.0.1.2.0, 16.0.1.2.0.1, 16.0.1.2.0.2, 16.0.1.2.0.4, 16.0.1.2.0.6, 16.0.1.2.0.7, 16.0.1.2.0.10, 16.0.1.2.0.12, 16.0.1.2.0.13, 16.0.1.2.0.15, 16.0.1.2.0.16, 16.0.1.2.0.19, 16.0.2.0.0, 16.0.2.1.0)
ERROR: No matching distribution found for odoo-addon-commission<17.1dev,>=17.0dev
Error: Process completed with exit code 1.
```
Any guess how to tackle this?

2024-01-24 06:13 UTC, ambientWave commented
@pedrobaeza Currently, there's a method named 'action_switch_invoice_into_refund_credit_note' that is called from 'account.move' model which seems to exist no more.

As a quick solution, I had ported the method from Odoo 16.0 and pasted it inside the inherited account.move. Odoo tests are passed.

But I have noticed that this method has a new name and has been slightly changed in Odoo 17.0:
```
    def action_switch_move_type(self):
        if any(move.posted_before for move in self):
            raise ValidationError(_("You cannot switch the type of a posted document."))
        if any(move.move_type == "entry" for move in self):
            raise ValidationError(_("This action isn't available for this document."))

        for move in self:
            in_out, old_move_type = move.move_type.split('_')
            new_move_type = f"{in_out}_{'invoice' if old_move_type == 'refund' else 'refund'}"
            move.name = False
            move.write({
                'move_type': new_move_type,
                'partner_bank_id': False,
                'currency_id': move.currency_id.id,
            })
            if move.amount_total < 0:
                move.write({
                    'line_ids': [
                        Command.update(line.id, {'quantity': -line.quantity})
                        for line in move.line_ids
                        if line.display_type == 'product'
                    ]
                })
```

instead of this in Odoo 16.0:
```

    def action_switch_invoice_into_refund_credit_note(self):
        if any(move.move_type not in ('in_invoice', 'out_invoice') for move in self):
            raise ValidationError(_("This action isn't available for this document."))

        for move in self:
            move.write({
                'move_type': move.move_type.replace('invoice', 'refund'),
                'partner_bank_id': False,
                'currency_id': move.currency_id.id,
            })
            if move.amount_total < 0:
                move.write({
                    'line_ids': [
                        Command.update(line.id, {'quantity': -line.quantity})
                        for line in move.line_ids
                        if line.display_type == 'product'
                    ]
                })
```

What would you recommend?

2024-01-30 15:44 UTC, pedrobaeza commented
You have to look for the equivalence of that method in this new version. That method was called for converting a normal invoice into a refund one and vice versa. How is this done now in v17? Once you find it, you have to make it work the same.

2024-01-31 11:10 UTC, ambientWave commented
```
    def action_switch_move_type(self):
        if any(move.posted_before for move in self):
            raise ValidationError(_("You cannot switch the type of a posted document."))
        if any(move.move_type == "entry" for move in self):
            raise ValidationError(_("This action isn't available for this document."))

        for move in self:
            in_out, old_move_type = move.move_type.split('_')
            new_move_type = f"{in_out}_{'invoice' if old_move_type == 'refund' else 'refund'}"
            move.name = False
            move.write({
                'move_type': new_move_type,
                'partner_bank_id': False,
                'currency_id': move.currency_id.id,
            })
            if move.amount_total < 0:
                move.write({
                    'line_ids': [
                        Command.update(line.id, {'quantity': -line.quantity})
                        for line in move.line_ids
                        if line.display_type == 'product'
                    ]
                })
```

This is the method that we're looking for. I would paste the contents thereof under the old inherited method name? Is this approach any good?

2024-01-31 11:15 UTC, pedrobaeza commented
You mustn't copy/paste anything. Just inherit and adapt the proper method.

2024-02-01 15:10 UTC, ambientWave commented
@pedrobaeza Adapted successfully!

2024-02-22 07:41 UTC, pedrobaeza commented
/ocabot migration account_commission

2024-04-15 14:16 UTC, Tisho99 commented
Hi @ambientWave 

I have also been reviewing this PR locally, and looks nice.

However, can you do the following to complete the migration?:
- Review and/or apply the changes i have made [on my branch](https://github.com/sygel-technology/commission/commit/8214b50a3c3a74024f9447627be19c892f35aeff). Some are upgrades and other [will be required for the migration](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0)
- Squash all the commits and execute pre-commit to pass the first check

With this changes i think the PR will be ready

Thank you!

2024-04-17 14:21 UTC, ambientWave commented
Hey @Tisho99

I have applied the requested changes. Could you check out the PR and review those?

2024-04-17 14:48 UTC, Tisho99 commented
@ambientWave 

Yes, thank you.

Let me some time, i think tomorrow i will have it reviewed

2024-04-18 12:04 UTC, Tisho99 requested changes

2024-04-18 12:04 UTC, Tisho99 commented on account_commission/views/account_move_views.xml
> +                <field name="any_settled" invisible="1" />
``
```suggestion
                <field name="settlement_id" column_invisible="1" />
                <field name="commission_free" column_invisible="1" />
                <field name="any_settled" column_invisible="1" />
```

2024-04-19 07:46 UTC, ambientWave commented on account_commission/views/account_move_views.xml
> +                <field name="any_settled" invisible="1" />
@Tisho99

Applied the changes!

2024-04-19 10:13 UTC, Tisho99 approved these changes
LGTM! Functional and technical review

2024-04-22 07:19 UTC, Tisho99 commented
Hi @ambientWave 

Your migration of commission was merged 

Can you remove the test-requirements.txt commit?

Thank you!

2024-04-24 17:46 UTC, ambientWave commented
@Tisho99

test-requirements.txt commit was dropped. All checks are passed

2024-04-26 08:12 UTC, Jaimermaccione approved these changes
LGTM! Functional review on runboot.

I'd like to comment on two minor issues :

- The README should correctly locate the "Agent" checkbox under the "Sales and Purchases" tab; it is currently found below the "Tax ID."

- Clarification is needed on the "Regenerate Agents" button. From my experience, it must be clicked to apply new commission type configuration and settle commissions after changes are made. Perhaps updating the README and providing clear instructions on using the "Regenerate Agents" button, based on user experiences, will enhance the module's usability.

2024-04-26 11:17 UTC, pedrobaeza commented on account_commission/models/account_move.py
> +    def fields_view_get(
Replace this by `_get_view`

2024-05-05 12:34 UTC, ambientWave commented on account_commission/models/account_move.py
> +    def fields_view_get(
@pedrobaeza Method name was modified!

2024-05-06 12:06 UTC, Tisho99 requested changes

2024-05-06 12:06 UTC, Tisho99 commented on account_commission/models/account_move.py
> +        res = super().fields_view_get(
```suggestion
        res = super()._get_view(
```

2024-05-06 12:06 UTC, Tisho99 commented on account_commission/models/account_move.py
> +        res = super().fields_view_get(
Have you forgotten this?

2024-05-07 08:31 UTC, Tisho99 approved these changes

2024-05-07 08:43 UTC, Tisho99 commented
Sorry @ambientWave 

The get_view call is still no correct. Can you see [this example](https://github.com/odoo/odoo/commit/b03c227e885efa4ccdcad43ccb56ee10371b9284#diff-9d31094bdf7f812b4cc4adc3498384e42cc6477ada91f39ff7c33decf8b7268fR23)?

2024-05-07 08:51 UTC, Tisho99 requested changes
Sorry @ambientWave

Im afraid the get_view call is still no correct. Can you see [this example](https://github.com/odoo/odoo/commit/b03c227e885efa4ccdcad43ccb56ee10371b9284#diff-9d31094bdf7f812b4cc4adc3498384e42cc6477ada91f39ff7c33decf8b7268fR23)?

It is in the [v16 migration guide](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0)

2024-05-08 16:31 UTC, Tisho99 commented
Hi @ambientWave 

I have done a supersede. If you have time you can git cherry-pick the last commit of my branch and i will close the supersede.

https://github.com/sygel-technology/commission/commits/17.0-mig-account_commission_backup/

2024-05-10 10:28 UTC, jimhuds commented
Thanks both for upgrading this. @Tisho99 I just tried your edits and I'm getting a server error:

`RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 99, in lookup
    r = d[key]
  File "<decorator-gen-5>", line 2, in __getitem__
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('account.move', <function Model._get_view_cache at 0xf5ce83a80b80>, (585, 'tree', None, 'en_GB', None))`

This happens when I enable the account_commission module and try to view any invoices (list or form)

2024-05-11 09:55 UTC, pedrobaeza commented
Superseded by #524

2024-05-11 09:55 UTC, closed without merging