[fix] sale_commision fix research on field partner_agent_ids on multi…
OCA/commission pull request #502
Opened 2024-01-22 15:58 UTC by matteoopenf

…company env.

With the fix I retrieve only the order of the company the user is logged, otherwise actually is recovered all order correspond with the search

2024-02-22 14:21 UTC, patrickt-oforce approved these changes

2024-02-22 14:30 UTC, amosdisabatino approved these changes

2024-02-22 14:49 UTC, pedrobaeza requested changes
- Please don't add empty lines inside a method.
- The search should be for all the allowed companies, not the main one.

2024-03-01 15:02 UTC, matteoopenf commented
> * Please don't add empty lines inside a method.
> * The search should be for all the allowed companies, not the main one.

Hi @pedrobaeza , 

ok for the lines empty.
About "The search should be for all the allowed companies, not the main one." if have not that fix I recevi a securty error

2024-03-01 15:06 UTC, pedrobaeza commented
Well, the error should be in other part then, as allowed companies should be supported.

2024-03-01 15:10 UTC, matteoopenf commented
> Well, the error should be in other part then, as allowed companies should be supported.

I did a lot of debug to avoid the problem on the screen, but the error is caused because we try to  access to record of other company.

2024-03-01 15:26 UTC, matteoopenf commented on sale_commission/models/sale_order.py
> +                ("object_id.company_id", "=", self.env.company.id),
@pedrobaeza you mean  here should be ("object_id.company_id",   'in',  self.env.companies.ids) ?

2024-03-01 15:34 UTC, pedrobaeza commented on sale_commission/models/sale_order.py
> +                ("object_id.company_id", "=", self.env.company.id),
Yes

2024-08-04 12:31 UTC, closed without merging