[14.0] [IMP] sale_commission_geo_assign_product_domain: add tree view
OCA/commission pull request #528
Opened 2024-05-15 12:22 UTC by renda-dev

Added a tree view for `res.partner.commission.group`

2024-05-15 15:40 UTC, aleuffre requested changes
A couple of notes before it can be approved.

2024-05-15 15:40 UTC, aleuffre commented on sale_commission_geo_assign_product_domain/views/res_partner_commission_group_view.xml
> +        <field name="binding_view_types">tree</field>
**issue**: `binding_view_types` is used for actions that can be called from the `Action` menù (like Duplicate and Archive, for example)

Here I think you want to set `view_mode` instead.

2024-05-15 15:40 UTC, aleuffre commented on sale_commission_geo_assign_product_domain/views/res_partner_commission_group_view.xml
> +        <field name="type">ir.actions.act_window</field>
**chore**: Setting this `type` is not necessary, it's already implicit from the `model="ir.actions.act_window"`

2024-05-16 10:09 UTC, francesco-ooops approved these changes
Functional ok!

2024-05-17 09:00 UTC, aleuffre approved these changes
Code review, LGTM

2024-05-17 09:01 UTC, aleuffre commented
/ocabot merge minor

2024-05-17 09:07 UTC, merged