[MIG] sale_commission_salesman: Migration to 17.0
OCA/commission pull request #534
Opened 2024-06-14 17:33 UTC by CLaurelB

Changelog:
- Replace `attrs` with an expression for the `invisible` attribute in the view.

2024-06-14 17:34 UTC, CLaurelB commented
@luisg123v could you review, please?

2024-06-19 15:37 UTC, luisg123v requested changes

2024-06-19 15:37 UTC, luisg123v commented on sale_commission_salesman/README.rst
> +    :target: https://github.com/OCA/commission/tree/17.0/sale_commission_salesman
Commit title:

execution → autofixes

2024-06-19 20:33 UTC, CLaurelB commented on sale_commission_salesman/README.rst
> +    :target: https://github.com/OCA/commission/tree/17.0/sale_commission_salesman
Title updated.

2024-07-10 01:08 UTC, luisg123v approved these changes
LGTM :+1: 

@moylop260 could you review/merge, please?

Regards

CC @desdelinux

2024-07-10 03:06 UTC, moylop260 commented
/ocabot merge nobump

2024-07-10 03:07 UTC, moylop260 commented
/ocabot migration sale_commission_salesman

2024-07-10 04:53 UTC, merged