[IMP]account_commission: possibility to add payment date limit on set…
OCA/commission pull request #588
Opened 2024-12-20 10:08 UTC by matteonext

…tle commissions

2024-12-20 10:48 UTC, PicchiSeba requested changes
Code review

2024-12-20 10:48 UTC, PicchiSeba commented on account_commission/models/account_move.py
> +            True if self.commission_id.invoice_state == "paid" else False
**nitpick**: this expression could be simplified

```suggestion
            self.commission_id.invoice_state == "paid"
```

2025-02-28 10:55 UTC, odooNextev approved these changes
LGTM

2025-02-28 15:49 UTC, PicchiSeba commented on account_commission/wizards/commission_make_settle.py
> +        self.env.context = context_date_payment
**questiom**: aren't these operations equivalent to

```py
self.env.context["date_payment_to"] = self.date_payment_to
```
?

Or am I missing something?

2025-02-28 16:04 UTC, matteonext commented on account_commission/wizards/commission_make_settle.py
> +        self.env.context = context_date_payment
Hi @PicchiSeba, self.env.context is a frozendict, which is an immutable dictionary. Because of this, I couldn't add self.date_payment_to directly as you suggested.

2025-03-03 07:54 UTC, PicchiSeba approved these changes
Code review: LGTM

2025-03-03 08:08 UTC, matteonext commented
@pedrobaeza What do you think? is it possible to merge?

2025-03-03 08:17 UTC, pedrobaeza requested changes

2025-03-03 08:17 UTC, pedrobaeza commented on account_commission/wizards/commission_make_settle.py
> +        self.env.context = context_date_payment
Please use `with_context` decorator instead of a hard replacement of this type, as it's not guaranteed that the internal implementation will work with this kind of operations.

2025-03-03 08:29 UTC, PicchiSeba commented
> Please use with_context decorator instead of a hard replacement of this type, as it's not guaranteed that the internal implementation will work with this kind of operations.

@pedrobaeza 

Shouldn't we prefer this approach instead of `with_context`? The old context would be discarded entirely

2025-03-03 08:31 UTC, pedrobaeza commented
No, `with_context` can have an entire dict as argument or just a context key. Depending on which you select, you will have a replacement or just a new/edited key.

2025-04-10 07:55 UTC, TheMule71 commented on account_commission/wizards/commission_make_settle.py
> +        return super().action_settle()
Is this covered by a test? 
My doubt is that `self` gets reassigned locally. I'm not sure that `super()` w/o arguments uses local super. So I'm not sure it works.

I'd suggest the explicit syntax:

`return super(CommissionMakeSettle, self).action_settle()`

to make sure that it's the modified `self` that gets used.

2025-04-10 09:28 UTC, matteonext commented on account_commission/wizards/commission_make_settle.py
> +        return super().action_settle()
Hi @TheMule71, thanks for your review. I've just added a coverage test and it seems to work properly as it is now. Do you think it's better to make the syntax more explicit, as you mentioned? Thanks!

2025-04-10 14:31 UTC, TheMule71 commented on account_commission/wizards/commission_make_settle.py
> +        return super().action_settle()
No, it's not necessary.

2025-06-27 15:24 UTC, matteonext commented
@pedrobaeza merge?

2025-06-27 15:29 UTC, pedrobaeza commented
This is adding a bit of complication on the module for a specific case, but it's not too much overhead and it's tested, so let's continue.

/ocabot merge minor

2025-06-27 15:35 UTC, merged